apiVersion: apps/v1
kind: Deployment
metadata:
  name: com-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: com-control
  template:
    metadata:
      labels:
        app: com-control
    spec:
      containers:
      - name: com-control
        image: registry.digitalocean.com/devops-registry-vadym/control-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
          - name: Redis__ConnectionString
            value: redis:6379
          - name: BasePath
            value: /control
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      imagePullSecrets:
        - name: digital-ocean